- name: creating the user that is not exisist
  hosts: mongodb
  vars_prompt:
    - name: user
      prompt: "please enter the user do you want to create"
      private: False 
  tasks: 
  - name : checking the use exist or not 
    ansible.buitlin.command: id {{user}}
    register: result
    ignore_errors: True 
  - name: pritngi the useer 
    ansible.builtin.debug: 
      msg: "the result is {{result}}"
  - name: creating the user if not exisit 
    ansible.buitlin.user: 
      name: {{user}}
    when: result.rc !=0 