- name: first ansible play book 
  hosts: mongodb
  tasks:
  - name: checking the user is exixst or not
    ansible.builtin.command: id mohan 
    register: outout
  - name: printing the variables 
    ansible.builtin.debug:
      msg: "the output is {{outout}}"
   
     
    

  