- name: first ansible play book 
  hosts: mongodb
  tasks:
  - name: checking the user is exixst or not
    ansible.builtin.command: id mohan 
    register: outout
    ignore_errors: True
  - name: printing the variables 
    ansible.builtin.debug:
      msg: "the output is {{outout}}"
  - name: creating the user
    ansible.builtin.debug:
      msg: "creating the user is "
    when: outout.rc !=0
   
     
    

  